# Generated by Django 5.2.1 on 2025-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_short",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="short name"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="level"),
                ),
            ],
            options={
                "verbose_name": "division",
                "verbose_name_plural": "divisions",
                "ordering": ["level"],
            },
        ),
    ]
