# Generated by Django 5.2.1 on 2025-05-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Makuuchi', 'Makuuchi'), ('Juryo', 'Juryo'), ('Makushita', 'Makushita'), ('Sandanme', 'Sandanme'), ('Jonidan', 'Jonidan'), ('Jonokuchi', 'Jonokuchi'), ('Mae-zumo', 'Mae-zumo'), ('Banzuke-gai', 'Banzuke-gai')], editable=False, max_length=12)),
                ('level', models.PositiveSmallIntegerField(editable=False)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Heya',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Heya',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shusshin',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=32)),
                ('international', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Shusshin',
                'ordering': ['international', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Yokozuna', 'Yokozuna'), ('Ozeki', 'Ozeki'), ('Sekiwake', 'Sekiwake'), ('Komusubi', 'Komusubi'), ('Maegashira', 'Maegashira'), ('Juryo', 'Juryo'), ('Makushita', 'Makushita'), ('Sandanme', 'Sandanme'), ('Jonidan', 'Jonidan'), ('Jonokuchi', 'Jonokuchi'), ('Mae-zumo', 'Mae-zumo'), ('Banzuke-gai', 'Banzuke-gai')], editable=False, max_length=12)),
                ('level', models.PositiveSmallIntegerField(editable=False)),
                ('order', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('direction', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West')], editable=False, max_length=4, null=True)),
                ('division', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='app.division')),
            ],
            options={
                'ordering': ['level', 'order', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='Rikishi',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('sumodb_id', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('nsk_id', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('name_jp', models.CharField(max_length=64)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('debut', models.DateField(blank=True, null=True)),
                ('intai', models.DateField(blank=True, null=True)),
                ('heya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rikishi', to='app.heya')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rikishi', to='app.rank')),
                ('shusshin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rikishi', to='app.shusshin')),
            ],
            options={
                'verbose_name_plural': 'Rikishi',
                'ordering': ['name'],
            },
        ),
    ]
