# Generated by Django 5.2.1 on 2025-06-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_basho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('slug', models.SlugField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Yokozuna', 'Yokozuna'), ('Ozeki', 'Ozeki'), ('Sekiwake', 'Sekiwake'), ('Komusubi', 'Komusubi'), ('Maegashira', 'Maegashira'), ('Juryo', 'Juryo'), ('Makushita', 'Makushita'), ('Sandanme', 'Sandanme'), ('Jonidan', 'Jonidan'), ('Jonokuchi', 'Jonokuchi'), ('Mae-zumo', 'Mae-zumo'), ('Banzuke-gai', 'Banzuke-gai')], editable=False, max_length=20)),
                ('level', models.PositiveSmallIntegerField(editable=False)),
                ('order', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('direction', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West')], editable=False, max_length=4, null=True)),
                ('division', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='app.division')),
            ],
            options={
                'ordering': ['division__level', 'level', 'order', 'direction'],
                'unique_together': {('title', 'order', 'direction', 'division')},
            },
        ),
    ]
