# Generated by Django 5.2.1 on 2025-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_bashohistory_meta"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="bashohistory",
                    name="shikona_en",
                    field=models.CharField(
                        default="", max_length=64, blank=True
                    ),
                ),
                migrations.AddField(
                    model_name="bashohistory",
                    name="shikona_jp",
                    field=models.CharField(
                        default="", max_length=64, blank=True
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
