# Generated by Django 5.2.1 on 2025-06-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_heya_shusshin_rikishi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BashoHistory',
            fields=[
                ('pk', models.CompositePrimaryKey('rikishi_id', 'basho_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('shikona_en', models.CharField(blank=True, default='', max_length=64)),
                ('shikona_jp', models.CharField(blank=True, default='', max_length=64)),
                ('basho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='app.basho')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rank')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to='app.rikishi')),
            ],
            options={
                'verbose_name_plural': 'Basho history',
                'ordering': ['basho__year', 'basho__month', 'rikishi_id'],
                'indexes': [models.Index(fields=['rikishi', 'basho'], name='app_bashohi_rikishi_ad2bd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('rikishi', 'basho'), name='unique_rikishi_basho')],
            },
        ),
    ]
