# Generated by Django 5.2.1 on 2025-06-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bashohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('match_no', models.PositiveSmallIntegerField()),
                ('east_shikona', models.CharField(max_length=64)),
                ('west_shikona', models.CharField(max_length=64)),
                ('kimarite', models.CharField(max_length=32)),
                ('basho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='app.basho')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts', to='app.division')),
                ('east', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts_as_east', to='app.rikishi')),
                ('west', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts_as_west', to='app.rikishi')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouts_won', to='app.rikishi')),
            ],
            options={
                'verbose_name_plural': 'Bouts',
                'ordering': ['basho__year', 'basho__month', 'day', 'match_no'],
                'indexes': [models.Index(fields=['basho', 'division', 'day'], name='app_bout_basho_i_fee811_idx')],
                'constraints': [models.UniqueConstraint(fields=('basho', 'day', 'match_no', 'east', 'west'), name='unique_bout')],
            },
        ),
    ]
