# Generated by Django 5.2.3 on 2025-06-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['division__level', 'order', 'direction']},
        ),
        migrations.RemoveField(
            model_name='rank',
            name='level',
        ),
    ]
