# Generated by Django 5.2.3 on 2025-06-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_rank_options_remove_rank_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rikishi',
            options={'verbose_name_plural': 'Rikishi'},
        ),
    ]
