# Generated by Django 5.2.3 on 2025-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bashorating_previous_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bashorating',
            new_name='app_bashora_rikishi_811c00_idx',
            old_name='app_bashora_rikishi_e02e83_idx',
        ),
        migrations.AlterField(
            model_name='rikishi',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rikishi',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
